version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/interactive-demo"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/web-component"
    schedule:
      interval: "daily"